//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperPathologyApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIDEPC\\SQL_2014;Initial Catalog=SuperPathDb_SM;Integrated Security=Tr" +
            "ue")]
        public string SuperPathDb_SMConnectionString {
            get {
                return ((string)(this["SuperPathDb_SMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIDEPC\\SQL_2014;Initial Catalog=SuperPathDb_Digital;Integrated Securi" +
            "ty=True")]
        public string SuperPathDb_DigitalConnectionString {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIDEPC\\SQL_2014;Initial Catalog=SuperPathDb_DGT;Integrated Security=T" +
            "rue")]
        public string SuperPathDb_DGTConnectionString {
            get {
                return ((string)(this["SuperPathDb_DGTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local)\\SQL_2014;Initial Catalog=MyDb;Integrated Security=True")]
        public string MyDbConnectionString {
            get {
                return ((string)(this["MyDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIDEPC\\SQL_2014;Initial Catalog=SuperPathDb_Digital_Update;Integrated" +
            " Security=True")]
        public string SuperPathDb_Digital_UpdateConnectionString {
            get {
                return ((string)(this["SuperPathDb_Digital_UpdateConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-03PGO57\\SQL_2014;Initial Catalog=SuperPathDb_Digital_Update;I" +
            "ntegrated Security=True")]
        public string SuperPathDb_Digital_UpdateConnectionString1 {
            get {
                return ((string)(this["SuperPathDb_Digital_UpdateConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HIDEPC\\SQL_2014;Initial Catalog=SuperPathDb_Digital_NEW;Integrated Se" +
            "curity=True")]
        public string SuperPathDb_Digital_NEWConnectionString {
            get {
                return ((string)(this["SuperPathDb_Digital_NEWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-03PGO57\\SQL_2014;Initial Catalog=SuperPathDb_Digital_NEW;Inte" +
            "grated Security=True")]
        public string SuperPathDb_Digital_NEWConnectionString1 {
            get {
                return ((string)(this["SuperPathDb_Digital_NEWConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WORKPC11\\SQL_2014;Initial Catalog=SuperPathDb_Digital_NEW;Integrated " +
            "Security=True")]
        public string SuperPathDb_Digital_NEWConnectionString2 {
            get {
                return ((string)(this["SuperPathDb_Digital_NEWConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-F22D9GN;Initial Catalog=SuperPathDb_Pop;User ID=sa;Password=1" +
            "2345")]
        public string SuperPathDb_PopConnectionString {
            get {
                return ((string)(this["SuperPathDb_PopConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-F22D9GN;Initial Catalog=SuperPathDb_Digital;User ID=sa;Passwo" +
            "rd=12345")]
        public string SuperPathDb_DigitalConnectionString1 {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WORKPC11\\SQL_2014;Initial Catalog=SuperPathDb_Digital;Integrated Secu" +
            "rity=True")]
        public string SuperPathDb_DigitalConnectionString2 {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GHOST\\SQL2014;Initial Catalog=SuperPathDb_Digital;User ID=sa;Password" +
            "=ra710983")]
        public string SuperPathDb_DigitalConnectionString3 {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OPTIMUS\\SQL2014;Initial Catalog=SuperPathDb_Digital;Integrated Securi" +
            "ty=True")]
        public string SuperPathDb_DigitalConnectionString4 {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UCH1SN3;Initial Catalog=SuperPathDb_Digital;Integrated Securi" +
            "ty=True")]
        public string SuperPathDb_DigitalConnectionString5 {
            get {
                return ((string)(this["SuperPathDb_DigitalConnectionString5"]));
            }
        }
    }
}
